chi_input_dim: 2
e_input_dim: 1
xi_input_dim: 1

h_hidden_dim: 256
chi_hidden_dim: 32
e_hidden_dim: 64
xi_hidden_dim: 16

num_encoder_layers: 9
num_decoder_layers: 3
dropout: 0.0
auto_encoder_h_out_dim: 1
auto_decoder_h_in_dim: 1


auto_encoder_gcp_layers: 1
auto_decoder_gcp_layers: 3
latent_diffusion_gcp_layers: 9